/*
 * Inline.h
 *
 *  Created on: May 9, 2021
 *      Author: michi
 */

#pragma once

namespace kaba {

enum class InlineID {
	None = -1,
	FloatToInt32,
	Float32ToFloat64,
	Float64ToFloat32,
	Int32ToFloat32,
	Int32ToInt64,
	Int64ToInt32,
	Int32ToInt8,
	Int8ToInt32,
	Int32ToUint8,
	Uint8ToInt32,
	PointerToBool,
	ComplexSet,
	VectorSet,
	RectSet,
	ColorSet,

	PointerAssign,
	PointerEqual,
	PointerNotEqual,

	Int8Assign,
	Int8Equal,
	Int8NotEqual,
	Int8Greater,
	Int8GreaterEqual,
	Int8Smaller,
	Int8SmallerEqual,
	Int8Add,
	Int8AddAssign,
	Int8Subtract,
	Int8SubtractAssign,
	Int8BitAnd,
	Int8BitOr,
	Int8Negative,
	Uint8Greater,
	Uint8GreaterEqual,
	Uint8Smaller,
	Uint8SmallerEqual,

	BoolAssign,
	BoolEqual,
	BoolNotEqual,
	BoolAnd,
	BoolOr,
	BoolNot,

	Int16ToInt32,
	Int16AssignInt32,

	Int32Assign,
	Int32Add,
	Int32AddAssign,
	Int32Subtract,
	Int32SubtractAssign,
	Int32Multiply,
	Int32MultiplyAssign,
	Int32Divide,
	Int32DivideAssign,
	Int32Modulo,
	Int32Equal,
	Int32NotEqual,
	Int32Greater,
	Int32GreaterEqual,
	Int32Smaller,
	Int32SmallerEqual,
	Int32BitAnd,
	Int32BitOr,
	Int32BitXOr,
	Int32ShiftRight,
	Int32ShiftLeft,
	Int32Negative,
	Int32Increase,
	Int32Decrease,

	Int64Assign,
	Int64Add,
	Int64AddInt32,
	Int64AddAssign,
	Int64Subtract,
	Int64SubtractAssign,
	Int64Multiply,
	Int64MultiplyAssign,
	Int64Divide,
	Int64DivideAssign,
	Int64Modulo,
	Int64Equal,
	Int64NotEqual,
	Int64Greater,
	Int64GreaterEqual,
	Int64Smaller,
	Int64SmallerEqual,
	Int64BitAnd,
	Int64BitOr,
	Int64BitXOr,
	Int64ShiftRight,
	Int64ShiftLeft,
	Int64Negative,
	Int64Increase,
	Int64Decrease,

	Float32Assign,
	Float32Add,
	Float32AddAssign,
	Float32Subtarct,
	Float32SubtractAssign,
	Float32Multiply,
	Float32MultiplyAssign,
	Float32Divide,
	Float32DivideAssign,
	Float32Equal,
	Float32NotEqual,
	Float32Greater,
	Float32GreaterEqual,
	Float32Smaller,
	Float32SmallerEqual,
	Float32Negative,

	Float64Assign,
	Float64Add,
	Float64AddAssign,
	Float64Subtract,
	Float64SubtractAssign,
	Float64Multiply,
	Float64MultiplyAssign,
	Float64Divide,
	Float64DivideAssign,
	Float64Equal,
	Float64NotEqual,
	Float64Greater,
	Float64GreaterEqual,
	Float64Smaller,
	Float64SmallerEqual,
	Float64Negative,

	Vec2Add,
	Vec2AddAssign,
	Vec2Subtract,
	Vec2SubtarctAssign,
	Vec2MultiplySV,
	Vec2MultiplyVS,
	Vec2MultiplyAssign,
	Vec2DivideVs,
	Vec2DivideAssign,
	Vec2Negative,

	ComplexMultiply,
	ComplexMultiplyAssign,
	ComplexDivide,
	ComplexDivideAssign,

	ChunkAssign,
	ChunkEqual,
	ChunkNotEqual,
	Passthrough,

	Vec3Add,
	Vec3AddAssign,
	Vec3Subtract,
	Vec3SubtarctAssign,
	Vec3MultiplyVV,
	Vec3MultiplyVF,
	Vec3MultiplyFV,
	Vec3MultiplyAssign,
	Vec3DivideVF,
	Vec3DivideAssign,
	Vec3Negative,

	SharedPointerInit,
};

}
